// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwf92WWJbejJuwjBM6_pGn6MbjRHL_JA',
    appId: '1:403846317102:web:a63cbec895859f76490bbf',
    messagingSenderId: '403846317102',
    projectId: 'dropdown-proje',
    authDomain: 'dropdown-proje.firebaseapp.com',
    storageBucket: 'dropdown-proje.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPsDM_qZglW-S7uycGPHUwLGsNLwCZdk',
    appId: '1:403846317102:android:d6d943b294795b26490bbf',
    messagingSenderId: '403846317102',
    projectId: 'dropdown-proje',
    storageBucket: 'dropdown-proje.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBpRcWGsbpxHSG3VyIfcYxjyIsLnbruYU',
    appId: '1:403846317102:ios:696885fa4e2d7bdf490bbf',
    messagingSenderId: '403846317102',
    projectId: 'dropdown-proje',
    storageBucket: 'dropdown-proje.appspot.com',
    iosClientId: '403846317102-6pam3qmd0erf8bnsqlg9sgivjjsokpcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDropdownProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBpRcWGsbpxHSG3VyIfcYxjyIsLnbruYU',
    appId: '1:403846317102:ios:a88d0413dd2f12a6490bbf',
    messagingSenderId: '403846317102',
    projectId: 'dropdown-proje',
    storageBucket: 'dropdown-proje.appspot.com',
    iosClientId: '403846317102-qvniou66tdoafasis1omeidp0jjs4q4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDropdownProject.RunnerTests',
  );
}
